// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfsf_DrtdsHSQcSX098uxSxpdjaisYcts',
    appId: '1:343865819084:web:388e5290d4999e13516769',
    messagingSenderId: '343865819084',
    projectId: 'ai-based-wild-animal-detection',
    authDomain: 'ai-based-wild-animal-detection.firebaseapp.com',
    storageBucket: 'ai-based-wild-animal-detection.firebasestorage.app',
    measurementId: 'G-E7J03GLG92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmUAaIBphRzQQ-xnFGqPO9jgOw5S6mIJw',
    appId: '1:343865819084:android:130303e863353213516769',
    messagingSenderId: '343865819084',
    projectId: 'ai-based-wild-animal-detection',
    storageBucket: 'ai-based-wild-animal-detection.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfsf_DrtdsHSQcSX098uxSxpdjaisYcts',
    appId: '1:343865819084:web:4dde890dc93f16fb516769',
    messagingSenderId: '343865819084',
    projectId: 'ai-based-wild-animal-detection',
    authDomain: 'ai-based-wild-animal-detection.firebaseapp.com',
    storageBucket: 'ai-based-wild-animal-detection.firebasestorage.app',
    measurementId: 'G-XNHP07S3ZS',
  );
}
